### PR TITLE
Enable xdebug in docker environment

### PR DESCRIPTION
**Pull request by Partyschaum**

### CODE REVIEW

**Comment by SharktheFire** [comment]
In the first commit `Enable xdebug in docker environment` xdebug will be installed in the container via Dockerfile. 
The part with '--add-host' adds entries to the container host, so the container host can connect to xdebug.
`xdebug.ini` configures xdebug.

**Comment by SharktheFire** [comment]
In the second commit `Moved xdebug config to Dockerfile.debug` moves xdebug to a new file called `Dockerfile.debug`.
The commit also adds a new rule to the Makefile called `build-debug`. This generates the container with xdebug.

**Comment by SharktheFire** [comment]
In the third commit `Enable xdebug in docker environment` was $DEBUG_IF removed, because `docker-machine inspect jimdo --format '{{ .Driver.HostOnlyCIDR}}'` gets the IP of xdebug.

**Comment by Partyschaum** [comment]
Ok, that's a very obvious description of what every commit does. Maybe I need to be more exact next time. What I meant by **explanation** was something like:

>  "The `Dockerfile.debug` extends the existing `Dockerfile` by installing the *xdebug* PHP extension from the PECL repository. Afterwards the installed *xdebug* extension is activated via the built in `docker-php-ext-enable` helper."

The idea behind letting you write such explanations is to evoke questions in you which you in turn are keen and curious about to answer like "What was this `FROM` declaration in the `Dockerfile` doing again? Ahh, I can extend conainers!". You get the point? 😁 

I want you to really understand the changes made. What does it mean to pass `--add-host` as parameter to a docker command? What are the purpose of the different configurations in the `xdebug.ini`? E.g. you could not only read the documentation about `--add-host` but even start up a container to see what are the effects of this parameter! Be little crazy scientists who want to explore everything! :man_facepalming: 

To say it in german: "Das war schon gar nicht mal so schlecht! Probiert es doch noch ein mal." 😄

**Comment by SharktheFire** [comment]
**1. Commit** First of all Hauke implemented the extension `xDebug` to the normal `Dockerfile`. 

> RUN pecl install xdebug \
>    && docker-php-ext-enable xdebug

The command `RUN pecl` installs xdebug via the PECL repository. PECL is a repository for all available PHP extensions. The built-in command `docker-php-ext-enable` activate the extension `xdebug`.

> COPY xdebug.ini /usr/local/etc/php/conf.d

This command copy the file `xdebug.ini` to the path `/usr/local/etc/php/conf.d` in the container.

>if [ -z ${DEBUG_IF+x} ]; then
    [..]
    exit
fi

Afterwards he added an if statement to the `run-server.sh` to make sure that the `${DEBUG_IF+x}` variable is set. This could be necessary to "communicate" with xdebug via the browser interface.

> --add-host="docker_host:$(ifconfig $DEBUG_IF | awk '$1 == "inet" {print $2}')"

This command in `docker run` bind xDebug as an external host to the main container jimdo/reportbook.  

- > docker_host:$(ifconfig $DEBUG_IF

This part set the environment variable $DEBUG_IF as a new docker-host name. 

- > | awk '$1 == "inet" {print $2}')"

This part display the word after the first coming word "inet". `awk` is a script lanquage similar `grep`. 

Either `$DEBUG_IF` is set or the second part will take place with `awk`.

The file `xdebug.ini` configure xdebug for the container.

>[xdebug]
xdebug.remote_enable=On
xdebug.remote_autostart=Off
xdebug.remote_connect_back=Off
xdebug.remote_host=docker_host

The command `xdebug.remote_enable=On` turns the debugger on. `xdebug.remote_autostart=Off` disable the possibilty of xDebug to start debugging if `get, post, cookie variables` are not setting. `xdebug.remote_connect_back=Off` turns the chance off xdebug to connect to the client that made the HTTP request. And `xdebug.remote_host` select the correct host where xdebug should running. In this case the env variable `docker_host` is the host for xdebug `($DEBUG_IF or awk  '$1 == "inet" {print $2}')`.

**Comment by SharktheFire** [comment]
**2. Commit** The second part Hauke and Pirmin moved the installing xdebug part from the normal `Dockerfile` to a new file called `Dockerfile.debug`. This file extends with the command `FROM` from the main container `jimdo\reportbook.
The settings in this file are the same like before in `Dockerfile`. 

Then they built a shellscript command in `Makefile` - `build-debug:`. 
This command build a completely docker container contains the xdebug extension. 
> docker build -t $(IMAGE):debug -f Dockerfile.debug

The name of the repository will be $(IMAGE) and the tag of the container is `:debug` with the file Dockerfile.debug.

In the `run-server.sh` they modified the `-add--host` command to create a docker image. 

> --add-host="docker_host:$(docker-machine inspect jimdo --format '{{ .Driver.HostOnlyCIDR}}' | awk -F/ '{print $1}')" \
     jimdo/reportbook:debug

Now the command will search the correct `docker_host` env variable with the docker-machine `inspect` command.   

> --format '{{ .Driver.HostOnlyCIDR}}'

This part format the host IP. To make sure that it does not clash with the specified main IP of jimdo\reportbook, `Driver.HostOnlyCIDR`make only subnets available between .1 and .25!

> \ jimdo/reportbook:debug

At the end of the command the response will pipe to the `jimdo\reportbook:debug` container.

**Comment by SharktheFire** [comment]
**3. Commit** The third part removed obsolete if statement in `run-server.sh`. The `${DEBUG_IF+x}`is not neccessary because of `docker-machine inspect jimdo`. 

Now the docker_host IP for xdebug will be create randomly with `'{{ .Driver.HostOnlyCIDR}}'` to make sure that the `jimdo\reportbook IP` does not clash with the IP of xdebug.

**Comment by SharktheFire** [comment]
**4. Commit** Hauke prepared the installing procedure of Visual Studio Code. He add the `.vscode` to `.gitignore`. So the settings of Visual Studio Code will not commit to GitHub and the local needed settings for xdebug can be make.

**Comment by SharktheFire** [comment]
**5. Commit** Hauke fixed the command for running a docker image.

> --add-host="docker_host:$(docker-machine inspect --format '{{ .Driver.HostOnlyCIDR}}' | awk -F/ '{print $1}')"

He removed the `jimdo` part after inspect. `jimdo` failed because of

1.  no container is running with this name.
-> ```Host does not exist: "jimdo"
invalid argument "docker_host:" for --add-host=docker_host:: invalid IP address in add-host: ""```

**Pull request merged**
